<%
  if ! Rails.env.production? && !Rails.env.staging?
    database_environment = BranchDb::SmartDatabaseEnvironment.new
    db_user = database_environment.user_name
    db_password = database_environment.password
    db_name = database_environment.database_name
    db_host = database_environment.host
    db_port = database_environment.port
  end
%>

default: &default
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  username:  <%= db_user %>
  password:  <%= db_password %>
  database:  <%= db_name %>
  host:  <%= db_host %>
  <% if db_port.present? %>
  port:  <%= db_port %>
  <% end %>

development:
  <<: *default

test:
  <<: *default

<%
def determine_adapter
  if Gem.loaded_specs.key?("mysql2")
    "mysql2"
  else
    "mysql"
  end
rescue
  "mysql"
end
%>

production:
  adapter:    <%= determine_adapter %>
  database:   '<%= ENV.fetch("DATABASE_NAME") { "DEFAULT_DATABASE_NAME" } %>'
  username:   '<%= ENV.fetch("DATABASE_USERNAME") { "DEFAULT_DATABASE_USERNAME" } %>'
  password:   '<%= ENV.fetch("DATABASE_PASSWORD") { "DEFAULT_DATABASE_PASSWORD" } %>'
  host:       '<%= ENV.fetch("DATABASE_HOST") { "DEFAULT_DATABASE_HOST" } %>'
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding:   utf8mb4
  collation:  utf8mb4_unicode_ci
  reconnect:  true
